### ISSUE TITLE
msolve (PDL::LinearAlgebra)  problems with scalar complex

### ISSUE THREAD

**Issue by guillepo** [PDLPorters/pdl-linearalgebra#11]
Dear development,
please check the trivial case
```
$A=[[i(),0],[0,i()]];
$B=[[1],[1]]]->r2C;
$X=msolve($A,$B);
```
seems that LU decomposition in not using the proper complex library
Regrads

**Comment by mohawk2** [comment]
I transferred this from `pdl` because it's a PDL::LinearAlgebra problem. However, I now see you've reported the same issue in #10 so I'll close this and track the issue there. Thank you for the report!
