### ISSUE TITLE
Missing [io] from Pars argument

### ISSUE THREAD

**Issue by wlmb** [PDLPorters/pdl-linearalgebra#28]
gtsv from PDL::LinearAlgebra::Complex and maybe other routines (I haven't checked yet) modify some of their arguments, though they do not declare them as [io] arguments.

**Comment by mohawk2** [comment]
See the Changes file for the ones that did need changing - it was a few, actually! I've addressed this now because it connects with the remaining type-conversion issues in main PDL.

Thanks for the report!
